### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by VblDigital** [vbopenclass/Project7#8]

**Comment by blanselle** [comment]
https://github.com/KnpLabs/KnpPaginatorBundle

**Comment by VblDigital** [comment]
#24

**Comment by VblDigital** [comment]
To fix : pagination doesn't work with JMSSerializer, mandatory for Hateoas.
Follow the issue : https://github.com/KnpLabs/KnpPaginatorBundle/issues/525

**Comment by VblDigital** [comment]
#31
